name: Build APK

on:
  workflow_dispatch:
  push:
    paths:
      - "mobile/**"
      - ".github/workflows/build-apk.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: build
        with:
          workdir: mobile
          command: buildozer -v android debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: multiplayer-snake-apk
          path: mobile/bin/*.apk
